In [4]:
import numpy as np

In [22]:
arr=np.array([[1,10,15],
        [20,30,80],
        [12,30,80]])

In [21]:
#Calculate mean
np.mean(arr)

22.0

In [9]:
#Mean for each row
np.mean(arr,axis=1)

array([ 8.66666667, 43.33333333, 14.        ])

In [10]:
#Mean for each column
np.mean(arr,axis=0)

array([11.        , 17.66666667, 37.33333333])

In [11]:
#Sum for each row
np.sum(arr,axis=1)

array([ 26, 130,  42])

In [12]:
#Sum for each column
np.sum(arr,axis=0)

array([ 33,  53, 112])

In [19]:
np.median(arr)

15.0

In [23]:
np.mode(arr)

AttributeError: module 'numpy' has no attribute 'mode'