In [19]:
np.array([1,10,15],
        [20,30,80],
        [12,13,17])

ValueError: only 2 non-keyword arguments accepted

In [15]:
import numpy as np

In [11]:
np.array(derr)

array([[ 1, 10, 15],
       [20, 30, 80],
       [12, 13, 17]])

In [16]:
derr=np.array(derr)

In [17]:
derr%2==0

array([[False,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

In [21]:
anon=np.array([[1,10,15],
        [20,30,80],
        [12,13,17]])

In [22]:
np.array(anon)

array([[ 1, 10, 15],
       [20, 30, 80],
       [12, 13, 17]])

In [23]:
anon%2==0

array([[False,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

In [24]:
anon[anon%2==0]

array([10, 20, 30, 80, 12])

In [30]:
anon2=anon[: , 1]

In [31]:
anon2[anon2%2==0]

array([10, 30])

In [42]:
anon2=anon[2 , 0]

In [44]:
anon2[anon2%2==0]

array([12])

In [45]:
anon[anon%2==1]

array([ 1, 15, 13, 17])

In [48]:
anon2=anon[2 , :]

In [49]:
anon2[anon2%2==1]

array([13, 17])

In [50]:
#converting odd num to even num
anon[anon%2==1]-1


array([ 0, 14, 12, 16])

In [51]:
anon[anon%2==1]=anon[anon%2==1]-1

In [52]:
anon

array([[ 0, 10, 14],
       [20, 30, 80],
       [12, 12, 16]])

In [53]:
anon=np.array(anon)

In [54]:
anon%2==0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [64]:
anon[anon%2==0]=anon[anon%2==0]**2

In [65]:
anon

array([[   0,  100,  196],
       [ 400,  900, 6400],
       [ 144,  144,  256]])

In [66]:
anon[anon%2==0]=anon[anon%2==0]//2

In [67]:
anon

array([[   0,   50,   98],
       [ 200,  450, 3200],
       [  72,   72,  128]])