In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
Social_Net=pd.read_csv('DataSets/Social_Network_Ads.csv')


In [3]:
Social_Net.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
Social_Net.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
y=Social_Net['Purchased']
x=Social_Net.drop('Purchased',axis=1)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3,random_state=1802)

In [8]:
x_train

User ID  Gender  Age  EstimatedSalary
266  15721592    Male   40            75000
117  15591433    Male   36            52000
132  15725660    Male   30            87000
185  15814816    Male   31            66000
210  15724536  Female   48            96000
..        ...     ...  ...              ...
219  15732987    Male   59           143000
397  15654296  Female   50            20000
142  15617134    Male   35            59000
19   15621083  Female   48            29000
39   15782806  Female   27            31000

[266 rows x 4 columns]

In [9]:
#To avoid dummy variable trap
x=pd.get_dummies(x,drop_first=True)


In [10]:
x

User ID  Age  EstimatedSalary  Gender_Male
0    15624510   19            19000            1
1    15810944   35            20000            1
2    15668575   26            43000            0
3    15603246   27            57000            0
4    15804002   19            76000            1
..        ...  ...              ...          ...
395  15691863   46            41000            0
396  15706071   51            23000            1
397  15654296   50            20000            0
398  15755018   36            33000            1
399  15594041   49            36000            0

[400 rows x 4 columns]

In [11]:
#cross validation
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3,random_state=1802)

In [13]:
#Feature scaling
from sklearn.preprocessing import StandardScaler

In [14]:
sc=StandardScaler()

In [15]:
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [16]:
#Model training
from sklearn.linear_model import LogisticRegression

In [17]:
lr=LogisticRegression(random_state=1802)

In [18]:
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1802, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
#Model prediction
lr_prediction=lr.predict(x_test)

In [20]:
lr_prediction

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1], dtype=int64)

In [21]:
#Model evaluation
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [22]:
accuracy_score(y_test,lr_prediction)

0.8507462686567164

In [23]:
print(classification_report(y_test,lr_prediction))

              precision    recall  f1-score   support

           0       0.80      0.97      0.88        73
           1       0.96      0.70      0.81        61

    accuracy                           0.85       134
   macro avg       0.88      0.84      0.84       134
weighted avg       0.87      0.85      0.85       134



In [36]:
cm=confusion_matrix(y_test,lr_prediction)

In [37]:
cm

array([[71,  2],
       [18, 43]], dtype=int64)

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rf_classifier=RandomForestClassifier(random_state=1802)

In [26]:
rf_classifier.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1802,
                       verbose=0, warm_start=False)

In [27]:
rf_prediction=rf_classifier.predict(x_test)

In [28]:
rf_prediction

array([1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1], dtype=int64)

In [29]:
print(classification_report(y_test,rf_prediction))

              precision    recall  f1-score   support

           0       0.89      0.92      0.91        73
           1       0.90      0.87      0.88        61

    accuracy                           0.90       134
   macro avg       0.90      0.89      0.89       134
weighted avg       0.90      0.90      0.90       134



In [38]:
#Using confusion matrix
cm=confusion_matrix(y_test,rf_prediction)

In [39]:
cm

array([[67,  6],
       [ 8, 53]], dtype=int64)

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
dt_classifier=DecisionTreeClassifier(random_state=1802)

In [32]:
dt_classifier.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1802, splitter='best')

In [33]:
dt_prediction=dt_classifier.predict(x_test)

In [34]:
dt_prediction

array([0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1], dtype=int64)

In [35]:
print(classification_report(y_test,dt_prediction))

              precision    recall  f1-score   support

           0       0.78      0.90      0.84        73
           1       0.86      0.69      0.76        61

    accuracy                           0.81       134
   macro avg       0.82      0.80      0.80       134
weighted avg       0.81      0.81      0.80       134

